management:
  security:
    enabled: false

jwt:
  secret: ${JWT_SECRET:QWERTYUIOKJHGFDS}

customer:
  authentication:
    expires: ${CUSTOMER_AUTHENTICATION_EXPIRES_IN:7200000}

google:
  client:
    id: ${GOOGLE_CLIENT_ID:131564184321-8o7d2rtmansr22v7hlubvjkqmqgkd08h.apps.googleusercontent.com}
spring:
  controller:
    name: customer-authentication
