management:
  security:
    enabled: false

jwt:
  secret: ${JWT_SECRET:QWERTYUIOKJHGFDS}

spring:
  application:
    name: order
    
cart:
  service:
    uri: http://cart/
payment:
  service:
    uri: http://payment/
inventory:
  service:
    uri: http://inventory/
